### ISSUE TITLE
panic: unable to open database file: out of memory (14)   

### ISSUE THREAD

**Issue by 8ball030** [minicloudlabs/helm-charts#48]
![image](https://user-images.githubusercontent.com/35799987/204091413-c599620f-5bb8-4b5e-be4c-95156e530e6e.png)

I get this issue on the default settings, I cant seem to set a user id or anything to work around it.

This might be relevant;
https://github.com/crazy-max/docker-firefox-syncserver/issues/14

**Comment by avakarev** [comment]
Hi @8ball030, please, let me know your k8s version and show your helmfile. I'm not sure what "default settings" means, did you used [this example](https://github.com/avakarev/gatus-chart#helmfileyaml-example) or you have no `values` at all?

**Comment by 8ball030** [comment]
Im really sorry i missed this btw.

**Comment by avakarev** [comment]
No worries, let me know if you have any more issues with the chart.
