### ISSUE TITLE
[Gatus chart] extraLabels not working on all resources

### ISSUE THREAD

**Issue by vanhoutenbos** [minicloudlabs/helm-charts#89]
Hi!

We are trying to apply labels to all resources using your `extraLabels`.
It seems like it does parse the `extraLabels` to the deployment but not down to the replicaset/pod.

# Potential bug

I believe there is a bug in the chart (if it is not by design).
I believe the 'baseLabels' should be added to the template labels here;
https://github.com/minicloudlabs/helm-charts/blob/96ec8a780929011dab14ee5528e15dee65262873/charts/gatus/templates/deployment.yaml#L24

# Technical

We use https://minicloudlabs.github.io/helm-charts
Version: 3.4.0

**Comment by PurseChicken** [comment]
I believe this is by design. extraLabels appear to be strictly for k8s metadata. If you want to add labels to the pods, then you probably want to use podLabels in values.

**Comment by vanhoutenbos** [comment]
Ah! I was looking for a object to add labels to for all resources I have both extra and pod labels for now
