### ISSUE TITLE
gatus: Allow security config to come from a secret

### ISSUE THREAD

**Issue by rouke-broersma** [minicloudlabs/helm-charts#95]
Currently all gatus config comes from a single configmap that is filled through the helm values. OIDC config contains a client secret, this should ideally be filled from a secret: https://github.com/TwiN/gatus?tab=readme-ov-file#oidc

**Comment by avakarev** [comment]
@rouke-broersma Just a quick heads-up that the this repository is no longer maintained.

Please, read gatus chart migration notes: https://github.com/minicloudlabs/helm-charts/tree/main/charts/gatus
