### ISSUE TITLE
Bad Yaml indent on youtrack _pod.tpl

### ISSUE THREAD

**Issue by Peelz** [minicloudlabs/helm-charts#96]
https://github.com/minicloudlabs/helm-charts/blob/07a756b25001f7e7587fe8ca37d33e91cb441ed7/charts/youtrack/templates/_pod.tpl#L59C15-L59C15

fixed by remove white space

**Comment by avakarev** [comment]
@Peelz Just a quick heads-up that the this repository is no longer maintained.
